unit Bridge.Model.Interfaces;

interface

uses
  System.Generics.Collections,
  FireDAC.Comp.Client,
  Bridge.Connection.Interfaces,
  Bridge.Connection.Types;

type
  /// <summary>
  /// Interface for the framework model layer.
  /// Defines methods for data access and CRUD operations.
  /// The Model encapsulates persistence logic and database access.
  /// </summary>
  IModel = interface
    ['{F4F2D0CB-F191-44DF-86E3-D4FDA9FF19FA}']

    /// <summary>
    /// Checks if a record exists with the specified value in a field.
    /// </summary>
    /// <param name="ATableName">Table name</param>
    /// <param name="AFieldName">Field name to check</param>
    /// <param name="AFieldValue">Value to search for</param>
    /// <returns>True if the value exists in the table</returns>
    function ExistsFieldValue(const ATableName, AFieldName, AFieldValue: string): Boolean;

    /// <summary>
    /// Checks if a record exists with the specified value, excluding an ID.
    /// Useful for uniqueness validation in Update operations.
    /// </summary>
    /// <param name="AId">Record ID to exclude from the check</param>
    /// <param name="ATableName">Table name</param>
    /// <param name="AFieldName">Field name to check</param>
    /// <param name="AFieldValue">Value to search for</param>
    /// <returns>True if the value exists in another record</returns>
    function ExistsFieldValueByID(const AId: Integer; const ATableName, AFieldName, AFieldValue: string): Boolean;

    /// <summary>
    /// Finds a record by its ID.
    /// </summary>
    /// <param name="ATableName">Table name</param>
    /// <param name="AId">Record ID</param>
    /// <returns>Query with the found record</returns>
    function Find(const ATableName: string; const AId: Integer): TFDQuery;

    /// <summary>
    /// Finds all records matching the specified criteria.
    /// </summary>
    /// <param name="ATableName">Table name</param>
    /// <param name="ACriteria">List of criteria</param>
    /// <returns>Query with filtered records</returns>
    function FindAll(const ATableName: string; const ACriteria: TList<TCriterion>): TFDQuery;

    /// <summary>
    /// Executes a custom SQL query and returns data in memory.
    /// </summary>
    /// <param name="ASQL">SQL command to execute</param>
    /// <returns>MemTable with query results</returns>
    function FindCustom(ASQL: string): TFDMemTable;

    /// <summary>
    /// Inserts a new record into the database.
    /// </summary>
    /// <param name="Sender">Object to insert</param>
    procedure Insert(Sender: TObject);

    /// <summary>
    /// Updates an existing record in the database.
    /// </summary>
    /// <param name="Sender">Object with updated data</param>
    procedure Update(Sender: TObject);

    /// <summary>
    /// Updates specific fields of an existing record in the database.
    /// Only the fields specified in AFieldsToUpdate will be modified.
    /// </summary>
    /// <param name="Sender">Object with updated data</param>
    /// <param name="AFieldsToUpdate">Array of property names to update</param>
    procedure UpdatePartial(Sender: TObject; const AFieldsToUpdate: TArray<string>);

    /// <summary>
    /// Removes a record from the database.
    /// </summary>
    /// <param name="Sender">Object to remove</param>
    procedure Delete(Sender: TObject);

    /// <summary>
    /// Restores a soft-deleted record in the database.
    /// </summary>
    /// <param name="Sender">Object to restore</param>
    procedure Restore(Sender: TObject);

    /// <summary>
    /// Starts a transaction in the database.
    /// </summary>
    procedure StartTransaction;

    /// <summary>
    /// Commits the current transaction.
    /// </summary>
    procedure Commit;

    /// <summary>
    /// Rolls back the current transaction.
    /// </summary>
    procedure Rollback;

    /// <summary>
    /// Checks if there is an active transaction.
    /// </summary>
    /// <returns>True if there is an active transaction</returns>
    function InTransaction: Boolean;

    /// <summary>
    /// Returns the last ID generated by the Insert operation.
    /// </summary>
    /// <returns>Last inserted ID</returns>
    function GetLastId: Variant;

    procedure InsertBatch(const AList: TObject; AClassType: TClass);
    procedure UpdateBatch(const AList: TObject; AClassType: TClass);
    procedure DeleteBatch(const AList: TObject; AClassType: TClass);

    /// <summary>
    /// Returns the connection used by this Model.
    /// </summary>
    function GetConnection: IConnection;

    function LoadNext(
      AClass: TClass;
      ALastItem: TObject;
      APageSize: Integer;
      const AOrderBy: TArray<TOrderByItem>;
      ACriteria: TList<TCriterion> = nil): TFDQuery;


    property Connection: IConnection read GetConnection;
  end;

implementation

end.
